name: Backend CD

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yaml"

concurrency:
  group: backend-cd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  packages: write

jobs:
  Build-and-Push:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the production Docker image
      - name: Build Docker Image
        run: |
          docker build \
          -t backend:prod-build \
          ./backend

      # Login to Docker Hub using secrets
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the image for Docker Hub
      - name: Tag Docker Image
        run: |
          docker tag backend:prod-build \
          ${{ secrets.DOCKER_HUB_USERNAME }}/ecom:backend-${{ secrets.IMAGE_TAG_VERSION }}

      # Push the tagged image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ecom:backend-${{ secrets.IMAGE_TAG_VERSION }}

  # Optional notifier job
  Notify:
    name: Notify on Telegram
    runs-on: ubuntu-latest
    needs: Build-and-Push
    if: always()   # Run even if deployment failed

    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ‚öôÔ∏è Backend CD Status

            üê≥ Docker Push: ${{ needs.Build-and-Push.result }}
            üîÅ Branch: ${{ github.ref_name }}
            üë§ Triggered by: ${{ github.actor }}
            üî¢ Image Tag: backend-${{ secrets.IMAGE_TAG_VERSION }}
            üì¶ Repo: ${{ github.repository }}

            ‚úîÔ∏è CD workflow finished.

