name: Backend CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yaml"

concurrency:
  group: backend-cd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  packages: write

jobs:

  Build-and-Push:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t backend:prod-build ./backend

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Image
        run: |
          docker tag backend:prod-build \
          ${{ secrets.DOCKER_HUB_USERNAME }}/ecom:backend-${{ secrets.IMAGE_TAG_VERSION }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ecom:backend-${{ secrets.IMAGE_TAG_VERSION }}

  Deploy-on-EC2:
    name: Deploy Backend (Blue-Green)
    runs-on: ubuntu-latest
    needs: Build-and-Push

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/ecom:backend-${{ secrets.IMAGE_TAG_VERSION }}"

            echo "Logging into Docker Hub"
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            echo "Deploying GREEN"
            ~/deploy/deploy_green.sh "$IMAGE"

            echo "Switching traffic to GREEN"
            ~/deploy/switch_to_green.sh

            echo "Finalizing BLUE -> GREEN promotion"
            ~/deploy/finalize_blue_cleanup.sh

            echo "Backend Blue-Green Deployment Completed Successfully!"
