name: Backend CI 

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"
concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  packages: write

jobs: 
  Lint:
    name: Lint Test
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name : setup node
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name : Run Lint
        working-directory: backend
        run: npm run lint

  Test:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: Lint

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run Test
        working-directory: backend
        run: npm test -- --watch=false

  Build-Scan: 
    name: Build and Scan Docker image
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
          -t backend:ci-build \
          ./backend

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: backend:ci-build
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          output: 'trivy-report.txt'
      - name: Upload Trivy report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-frontend-report
          path: trivy-report.txt
        if: always()
      - name: Save image as artifact
        run: |
          docker save backend:ci-build -o backend_build_ci.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image-clean
          path: backend_build_ci.tar

  Notify-On-Telegram:
    name: Notify on Telegram
    runs-on: ubuntu-latest
    needs: [Lint, Test, Build-Scan]
    if: always()

    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            âš™ï¸ PR Notifier From Backend CI

            ğŸ§¹ Lint Test: ${{ needs.Lint.result }}
            ğŸ§ª Unit Test: ${{ needs.Test.result }}
            ğŸ”¨ Docker Image Build: ${{ needs.Build-Scan.result }}

            ğŸ” Branch: `${{ github.ref_name }}`
            ğŸ§‘â€ğŸ’» Triggered by: `${{ github.actor }}`
            ğŸ“¦ Repository: `${{ github.repository }}`
