name: Backend CI 

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"
concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  packages: write

jobs: 
  Lint:
    name: Lint Test
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name : setup node
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name : Run Lint
        working-directory: backend
        run: npm run lint

  Test:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: Lint

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run Test
        working-directory: backend
        run: npm test -- --watch=false

  Build-Scan: 
    name: Build and Scan Docker image
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
          -t backend:ci-build \
          ./backend

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: backend:ci-build
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          output: 'trivy-report.txt'
      - name: Upload Trivy report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-frontend-report
          path: trivy-report.txt
        if: always()
  Notify-On-Telegram:
    name: Notify on Telegram
    runs-on: ubuntu-latest
    needs: [Lint, Test, Build-Scan]
    if: always()

    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            âš™ï¸ *Backend PR CI Report*

            ğŸ§ª *CI Status Summary*
            â”œâ”€ ğŸ§¹ Lint: *${{ needs.Lint.result }}*
            â”œâ”€ ğŸ§ª Tests: *${{ needs.Test.result }}*
            â””â”€ ğŸ³ Docker Build & Trivy Scan: *${{ needs.Build-Scan.result }}*

            ğŸ” *Pull Request Details*
            â”œâ”€ Title: *${{ github.event.pull_request.title }}*
            â”œâ”€ Author: `${{ github.actor }}`
            â””â”€ PR Link: ${{ github.event.pull_request.html_url }}

            ğŸ“Œ *Commit Info*
            â”œâ”€ SHA: `${{ github.sha }}`
            â””â”€ Message: "${{ github.event.pull_request.head.sha && github.event.pull_request.title }}"

            ğŸŒ¿ *Branch Information*
            â”œâ”€ Source Branch: `${{ github.head_ref }}`
            â””â”€ Target Branch: `${{ github.base_ref }}`

            ğŸ”— *Workflow Links*
            â””â”€ Run Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            âœ”ï¸ *CI Completed*
            Review results above before merging.
