#workflow name
name: Frontend CI 

#workflow metadata which trigger the flow
on:   
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    paths:  #only run on changes to frontend code or this workflow file
      - "frontend/**"
      - ".github/workflows/frontend-ci.yaml"
  push:
    branches:
      - main
    paths:  
      - "frontend/**"
      - ".github/workflows/frontend-ci.yaml"

#workflow settings - This prevents multiple runs from piling up when you push several commits quickly.
concurrency: 
  group: frontend-ci-${{ github.ref }} #Groups all runs for this workflow + this branch.
  cancel-in-progress: true #Cancels the previous run when a new commit arrives.

#workflow jobs
jobs:
  Lint: #Job name
    name: Lint test
    runs-on: ubuntu-latest

    steps: #steps for the job
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags 
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  #specify node version
          cache: 'npm'  #cache npm dependencies

      - name : Install dependencies
        working-directory: frontend
        run: npm ci  #install npm dependencies

      - name : Run lint
        working-directory: frontend
        run: npm run lint  #run lint command
    
  Test: 
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: Lint

    steps: 
      - name: checkout repositiry
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use  Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'

      - name : Install dependeccies
        working-directory: frontend
        run: npm ci

      - name: Run tests
        working-directory: frontend
        run: npm test -- --watch=false

  Build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run : |
          docker build \
          -t frontend:ci-build \
          ./frontend

      - name: Save image as artifact
        run: |
          docker save frontend:ci-build -o frontend_ci_build.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend-image.tar

  Scan-Image:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: Build

    steps: 
      - name: Download image artifact 
        uses: actions/download-artifact@v4
        with:
          name: frontend-image

      - name: Load Docker Image
        run: | 
          docker load -i frontend-image.tar

      - name: Run Trivy vulnurability scan
        uses: aquasecurity/trivy-action@v0.22.0
        with:
          image-ref: frontend:ci-build
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Optional step to upload the Trivy report as an artifact
      - name: Upload Trivy report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-frontend-report
          path: trivy-report.txt
        if: always()

  Push-To-Docker-Hub:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Push Frontend Image to Docker Hub
    runs-on: ubuntu-latest
    needs: Scan-Image

    steps:
      - name: Download image artifact   
        uses: actions/downlad-artifact@v4
        with:
          name: frontend-image

      - name: Load Docker Image
        run: | 
          docker load -i frontend-image.tar

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name : Tag Docker image
        run: |
          docker tag frontend:ci-build ${{ secrets.DOCKER_HUB_USERNAME }}/ecom-frontend:${{ secrets.IMAGE_TAG_VERSION}}

      - name : Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ecom-frontend:${secrets.IMAGE_TAG_VERSION} 

  Notify-On_Telegram:
    name: Notify on Telegram
    runs-on: ubuntu-latest
    needs: [Lint, Test, Build, Scan-Image, Push-To-Docker-Hub]

    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.3.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Frontend CI Pipeline Result:
            Lint: ${{ needs.Lint.result }}
            Test: ${{ needs.Test.result }}
            Build: ${{ needs.Build.result }}
            Scan Image: ${{ needs.Scan-Image.result }}
            Push to Docker Hub: ${{ needs.Push-To-Docker-Hub.result }}