#workflow name
name: Frontend CD

#workflow metadata - manual or can be automated later
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:  #only run on changes to frontend code or this workflow file
      - "frontend/**"
      - ".github/workflows/frontend-cd.yaml"

#workflow settings - prevent overlapping deployments
concurrency:
  group: frontend-cd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  packages: write

jobs:

  Build-and-Push:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the production Docker image
      - name: Build Docker Image
        run: |
          docker build \
          -t frontend:prod-build \
          ./frontend

      # Login to Docker Hub using secrets
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the image for Docker Hub
      - name: Tag Docker Image
        run: |
          docker tag frontend:prod-build \
          ${{ secrets.DOCKER_HUB_USERNAME }}/ecom:frontend-${{ secrets.IMAGE_TAG_VERSION }}

      # Push the tagged image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ecom:frontend-${{ secrets.IMAGE_TAG_VERSION }}
  
  Deploy-on-EC2:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    needs: Build-and-Push
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}/app
            echo "Logging in to Docker Hub..."
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            echo "Pulling latest frontend image..."
            docker compose pull frontend

            echo "Recreating frontend container..."
            docker compose up -d frontend

            echo "Removing old unused images..."
            docker image prune -f

            echo "Frontend deployment completed!"
